# Generated by Django 5.1.5 on 2025-07-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet de la demande')),
                ('message', models.TextField(verbose_name='Votre message')),
                ('sent_date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
            ],
            options={
                'verbose_name': 'Message de Contact',
                'verbose_name_plural': 'Messages de Contact',
                'ordering': ['-sent_date'],
            },
        ),
    ]
