# Generated by Django 5.1.5 on 2025-07-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('country_interest', models.CharField(choices=[('senegal', 'Sénégal'), ('burundi', 'Burundi'), ('rwanda', 'Rwanda'), ('gabon', 'Gabon'), ('all', 'Tous / Plusieurs')], max_length=20, verbose_name="Pays(s) d'intérêt")),
                ('travel_type', models.CharField(choices=[('aventure', 'Aventure & Safari'), ('culturel', 'Culturel & Historique'), ('nature', 'Nature & Randonnée'), ('detente', 'Détente & Plages'), ('affaires', 'Affaires & Urbain'), ('other', 'Autre')], max_length=50, verbose_name='Type de voyage souhaité')),
                ('description', models.TextField(verbose_name='Message / Besoins spécifiques')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
            ],
            options={
                'verbose_name': 'Demande de Voyage',
                'verbose_name_plural': 'Demandes de Voyages',
                'ordering': ['-request_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='touristsite',
            options={'ordering': ['name'], 'verbose_name': 'Site Touristique', 'verbose_name_plural': 'Sites Touristiques'},
        ),
        migrations.RemoveField(
            model_name='touristsite',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='touristsite',
            name='location',
        ),
        migrations.RemoveField(
            model_name='touristsite',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='touristsite',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville / Région'),
        ),
        migrations.AddField(
            model_name='touristsite',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_sites/'),
        ),
        migrations.AddField(
            model_name='touristsite',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_sites/'),
        ),
        migrations.AddField(
            model_name='touristsite',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='touristsite',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='touristsite',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='tourist_sites/', verbose_name='Image principale'),
        ),
        migrations.AlterField(
            model_name='touristsite',
            name='category',
            field=models.CharField(choices=[('nature', 'Nature & Faune'), ('culture', 'Culturel & Historique'), ('aventure', 'Aventure & Activités'), ('urbain', 'Urbain'), ('plage', 'Plage & Détente')], max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='touristsite',
            name='country',
            field=models.CharField(choices=[('senegal', 'Sénégal'), ('burundi', 'Burundi'), ('rwanda', 'Rwanda'), ('gabon', 'Gabon')], max_length=20, verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='touristsite',
            name='description',
            field=models.TextField(verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='touristsite',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom du site touristique'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
