# Generated by Django 5.1.5 on 2025-07-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('survey', 'Survey'), ('consultation', 'Consultation'), ('registration', 'Registration'), ('transfer', 'Transfer')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('user_request', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
