# Generated by Django 5.1.5 on 2025-07-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('country', models.CharField(choices=[('senegal', 'Sénégal'), ('burundi', 'Burundi'), ('rwanda', 'Rwanda'), ('gabon', 'Gabon')], max_length=20, verbose_name='Pays de la propriété')),
                ('service_type', models.CharField(choices=[('defrichage', 'Préparation et Défrichage des Terres'), ('analyse-sols', 'Analyse et Amélioration des Sols'), ('irrigation', "Installation de Systèmes d'Irrigation"), ('accompagnement-agricole', 'Accompagnement Achat/Location Terrains Agricoles'), ('other', 'Autre / Demande Générale')], max_length=50, verbose_name='Type de service souhaité')),
                ('description', models.TextField(verbose_name='Description détaillée du besoin')),
                ('desired_dates', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dates / Délais souhaités')),
                ('request_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
            ],
            options={
                'verbose_name': 'Demande de Service Foncier',
                'verbose_name_plural': 'Demandes de Services Fonciers',
                'ordering': ['-request_date'],
            },
        ),
        migrations.DeleteModel(
            name='LandService',
        ),
    ]
