# Generated by Django 5.1.5 on 2025-07-17 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField()),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Agent',
                'verbose_name_plural': 'Contacts Agents',
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-published_date'], 'verbose_name': 'Propriété', 'verbose_name_plural': 'Propriétés'},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='created_at',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='availability_status',
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, null=True, verbose_name='Commodités (séparées par des virgules)'),
        ),
        migrations.AddField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Nombre de salles de bain'),
        ),
        migrations.AddField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de chambres'),
        ),
        migrations.AddField(
            model_name='property',
            name='current_crops',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cultures actuelles/passées'),
        ),
        migrations.AddField(
            model_name='property',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Mise en avant'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_low_cost',
            field=models.BooleanField(default=False, verbose_name='Propriété à faible coût'),
        ),
        migrations.AddField(
            model_name='property',
            name='land_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface du terrain (m² ou hectares)'),
        ),
        migrations.AddField(
            model_name='property',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse exacte'),
        ),
        migrations.AddField(
            model_name='property',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='property',
            name='location_country',
            field=models.CharField(blank=True, choices=[('senegal', 'Sénégal'), ('burundi', 'Burundi'), ('rwanda', 'Rwanda'), ('gabon', 'Gabon')], max_length=20, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='property',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Image principale'),
        ),
        migrations.AddField(
            model_name='property',
            name='soil_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Type de sol'),
        ),
        migrations.AddField(
            model_name='property',
            name='surface_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Surface habitable (m²)'),
        ),
        migrations.AddField(
            model_name='property',
            name='water_access',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Accès à l'eau"),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(verbose_name='Description détaillée'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Prix (USD)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('house', 'Maison'), ('apartment', 'Appartement'), ('land', 'Terrain'), ('farmland', 'Terrain Agricole'), ('commercial', 'Commercial')], max_length=20, verbose_name='Type de propriété'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre de la propriété'),
        ),
        migrations.AlterField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'À Vendre'), ('rent', 'À Louer')], max_length=10, verbose_name='Type de transaction'),
        ),
        migrations.AddField(
            model_name='agentcontact',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_contacts', to='real_estate.property'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
